version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout

      - run:
          name: Install assetfinder
          command: |
            go install github.com/tomnomnom/assetfinder@latest
            chmod +x ~/go/bin/assetfinder

      - run:
          name: Find domains with assetfinder
          command: |
            ~/go/bin/assetfinder test.com > domains.txt

      - run:
          name: Display domains file
          command: cat domains.txt

      - run:
          name: Install notify
          command: |
            GO111MODULE=on go get -u github.com/projectdiscovery/notify/cmd/notify@latest

      - run:
          name: Send domains to Discord
          command: |
            notify -discord-webhook-url="https://discordapp.com/api/webhooks/1229117362461216869/s9R4dRmpW9tJD2C0mZUBYq-1Bs0bFTsBW8SZqbvKPsUV5H2jHDe70fSFh4cNiveedAW5" -message-file="domains.txt" -provider=discord
