version: 2.1

jobs:
  subdomain_scan:
    docker:
      - image: golang:latest
    steps:
      - run:
          name: Install assetfinder
          command: |
            go install github.com/tomnomnom/assetfinder@latest
      - run:
          name: Run assetfinder and save output
          command: |
            assetfinder hackdserone.com > subdomains.txt
      - persist_to_workspace:
          root: .
          paths:
            - subdomains.txt

  nuclei_scan:
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install nuclei
          command: |
            go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
      - run:
          name: Run nuclei and save output
          command: |
            nuclei -l subdomains.txt -severity low,medium,high,critical -o nuclei_result.txt
      - persist_to_workspace:
          root: .
          paths:
            - nuclei_result.txt

  notify:
    docker:
      - image: golang:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install notify
          command: |
            go install github.com/projectdiscovery/notify/cmd/notify@latest
      - run:
          name: Move config.yaml
          command: |
            mkdir -p /root/.config/notify/
            mv provider-config.yaml /root/.config/notify/
      - run:
          name: Send subdomain results to Discord
          command: |
            notify -id subs -i subdomains.txt
      - run:
          name: Send nuclei results to Discord
          command: |
            notify -id nuclei -i nuclei_result.txt

workflows:
  version: 2
  build:
    jobs:
      - subdomain_scan
      - nuclei_scan:
          requires:
            - subdomain_scan
      - notify:
          requires:
            - nuclei_scan
